### ISSUE TITLE
ember+ for webbrowser

### ISSUE THREAD

**Issue by infantilo** [DeutscheSoft/ember-plus#1]
Hi,
is there any way to adapt this script to be run from within an webbrowser?

**Comment by arneg** [comment]
The library does work in the Browser. In that situation you need to proxy the Ember+ tcp connection using a WebSocket. You can build a non es6 module bundle using `npm run build` which will create a file called `dist/ember-plus.browser.js`. This file, when loaded, will export a global symbol called `EmberPlus` which contains all exports.

**Comment by infantilo** [comment]
Many thanks for quick reply and help!
Sadly im getting the following error message, trying to build the non es6 bundle


` ember-plus@1.0.3 build
> ./node_modules/.bin/rollup -c rollup.config.js
'.' is not recognized as an internal or external command,
operable program or batch file.
`

**Comment by arneg** [comment]
What operating system are you using?

**Comment by infantilo** [comment]
i'm running on win10

**Comment by arneg** [comment]
To give a bit of background: 

The generated non es6 bundle is simply a bundled version of `src/index.browser.esm.js`. If you write your web application using es modules you don't need to create the bundle but should be able to import directly from that file.

If you do need a bundle, please remember to install rollup. I personally used `rollup@2.33.1` the last time I created the bundle. I would usually do something like

```
npm install --no-save rollup
npm run build
```
