### ISSUE TITLE
failing to address node with number greater than 127

### ISSUE THREAD

**Issue by domiFR** [DeutscheSoft/ember-plus#4]
in 'src/ber/relative_oid.js', the function relative_oid_encode doesn't work with number greater than 127.

I wrote this to make it work :

export function relative_oid_encode(data, pos, identifiers) {
	let MyLIFO = new Array(0);
	let b;
	for (let i = 0; i < identifiers.length; i++) {
		let n = identifiers[i];
	
	
		if (!(n >= 0))
			throw new TypeError('Relative OID entries need to be non-negative.');

		do {
			b = n & 0x7f;

			MyLIFO.push(b);

			n >>= 7;
		} while (n !== 0);
			
		while (MyLIFO.length > 0) {
			b = MyLIFO.pop();
			if (MyLIFO.length > 0) b |= 0x80; 
			data.setUint8(pos, b);
			pos++;
	};
	
	
  }

  return pos;
}

**Comment by arneg** [comment]
Thanks for the report, I will look into it.
