### ISSUE TITLE
getting issue with real number

### ISSUE THREAD

**Issue by domiFR** [DeutscheSoft/ember-plus#5]
I think there's some troubles with the functions in the file "src\ber\real.js", because I'm getting wrong values when reading some parameter described as "double" in the lawo ember+ viewer.

**function real_decode(data, pos, length)**

This function is attempting to get the exponent_length from the two lower bits of the first contents octet in data. But, according to  ITU-T X690 (02/2021) §8.5.7.4, it is the exponent format, with the following meanings :
- if 00, then second contents octet encodes the value of the exponent, which means exponent_length would be 1
- if 01, then second and third contents octets encode the value of the exponent, which means exponent_length would be 2
- if 10, then second, third, and fourth contents octets encode the value of the exponent, which means exponent_length would be 3
- if 11, you have to read the second contents octet to get the number of following octets used to encode the value of the exponent
The last case is ok, but the others seem confusing exponent format and exponent length which differ by 1.

This function is calculating mantissa using integer_decode(). I get some negative mantissa with this decoding function, leading to wrong value. I guess mantissa should be unsigned integer, while integer_decode() returns signed integer.

**function join_float64(value)**

with Float64, mantissa is stored in the 52 lower bits.
I couldn't understand why you add 52 to the exponent.
I tried without that adding, and it seems to work.

**function split_float64(value)**

Following what I did with join_Float64(), I modified split_Float64() the same way, but to be honest, I didn't test.

with Float64, mantissa is stored in the 52 lower bits.
I couldn't understand why you add or substract that value (52) to the exponent.
I tried a workaround :
- calculated sign and exponent look good to me.
- to get mantissa, i just didn't add 52 to the exponent.
- finally, I return [ sign, exponent, mantissa ], without substracting 52 to the exponent.

With those workarounds, I could get some right values for real numbers, matching what lawo ember+ viewer shows, except when integer_decode() returns an negative value for mantissa.

As I have very limited skills with programming, I still haven't find a workaround for decoding mantissa.

By the way, as I said that sometimes I didn't understand what you did, then, this also means I may be fully wrong with my workarounds.
If this the case, I apologise.

**Comment by arneg** [comment]
Hi @domiFR ,

first of all, thanks for this report. I was somehow suspecting that the float handling could be incomplete or buggy. We have never used this code with a device which uses floating point values.

To be honest, I was personally a little bit confused when implementing this code. The Real implementation that lawo published here [Real.hpp](https://github.com/Lawo/ember-plus/blob/master/libember/Headers/ember/ber/traits/Real.hpp) in my reading did not conform to the ASN.1 ber spec.

At the time I tried to find an open source C/C++ ASN.1 BER implementation which supports Real, however I was unable to find a good example.

Do you have test cases (e.g. floating point numbers and the correct BER encoding as bytes)?

**Comment by domiFR** [comment]
Hi Arne,

as I was searching for some Ember+ implementation, I found your's which was easier to test, thanks to your example (printDevice.js).
There are some others implementations that I didn't test.
For example : 
- https://github.com/evs-broadcast/node-emberplus
- https://github.com/sverigesradio
If you don't already know those implementations, They may show you other ways to encode and decode BER.

About test cases, I will try to catch some from my equipment (Jünger Aixpressor), using your code to get a dataview from incoming buffer, and assuming it is correctly BER encoded by this equipment.

**Comment by domiFR** [comment]
Hi,

I modified real.js and integer.js to use a new function : uinteger_decode(), to get mantissa decoded from incoming buffer.
Now it seems to work.
[new_real_integer.zip](https://github.com/DeutscheSoft/ember-plus/files/9402192/new_real_integer.zip)

**Comment by domiFR** [comment]
And here are some data send by my equipment : 

[test_new_real_integer.zip](https://github.com/DeutscheSoft/ember-plus/files/9402448/test_new_real_integer.zip)


I'm working with Node.JS and it has some limitations. It can't write more than 100 bytes from a dataview ; that's why there is a buffer100 (with decimal numbers) to get the full dataview.
The capture happens in the onMessage() function from connection.js
When function real_decode() is invoked, then I captured the all data used there.

Nota Bene : this was done using my workarounds.

**Comment by arneg** [comment]
Thanks for the additional info. I will look into this this week and hopefully get this fixed.

**Comment by arneg** [comment]
I have attempted to add test cases and looked again at the BER spec. I have pushed an attempt at fixing the encoding of real numbers on a branch called bugfix/5-real-encoding . Please try the code on that branch to see if it resolves the issue you see with your device.

**Comment by domiFR** [comment]
I tested, but it doesn't work well.
I will go deeper to give you a more detailed report.

**Comment by domiFR** [comment]
I found the problem.

in real.js, function join_float64(), you wrote :
u8[1] |= ieee_exponent << 4;

But formerly, it was :
u8[1] = (exponent << 4) & 0xf0;

changing that makes it works fine.

I also notice that function split_float64() wasn't changed ; there is still +52 and -52 to exponent. And I think you should rewrite it the same way you did with the new join_float64(). managing ieee_exponent, which is Uint, and exponent which is Int, makes  the code easier to understand.

Thanks for your job.

**Comment by arneg** [comment]
Thanks again for the review, I will rework this again and then integrate to the main branch!
